# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        carre: #nom du filtre
            quality: 75 #qualité de l'image
            filters:
                thumbnail:
                    size: [400,800]
                    mode: outbound
        echelle:
            quality: 85
            filters:
                scale:
                    dim: [400,400]

        evenement:
            quality: 80
            filters:
                upscale:
                    min: [900,800]
                thumbnail:
                    size: [700,400]
                    mode: outbound
               # watermark:
                 #   image: ../public/